- id: kitchen_light_on_if_motion
  alias: Küchenlicht an bei Bewegung
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000113c70a
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d000113c70a
    from: 'on'
    platform: state
    to: 'off'
  action:
    service: homeassistant.toggle
    data:
      entity_id: light.kuche
  
  # condition:
  # - condition: or
  #   conditions:
  #   - before: sunrise
  #     condition: sun
  #   - after: sunset
  #     condition: sun
  # - after: sunrise
  #   after_offset: '60'
  #   before: sunset
  #   before_offset: '60'
  #   condition: sun

- id: uli2
  alias: "T\xFCr \xF6ffnen, Licht an"
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00011c8d52
    platform: state
    to: 'on'
  # condition:
  # - condition: or
  #   conditions:
  #   - before: sunrise
  #     condition: sun
  #   - after: sunset
  #     condition: sun
  # - after: sunrise
  #   after_offset: '60'
  #   before: sunset
  #   before_offset: '60'
  #   condition: sun
  action:
    entity_id: light.flur
    service: homeassistant.turn_on


- id: uli1
  alias: Aufstehen unter der Woche
  trigger:
  - platform: time
    hours: 6
    minutes: 30
    seconds: 0
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
    service: homeassistant.turn_on
    entity_id: light.wohnung
    data:
      brightness: 50


- id: uli3
  alias: "Nachricht, wenn T\xFCr ge\xF6ffnet wird"
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00011c8d52
    to: 'on'
  action:
  - service: notify.slack_msg
    data:
      message: "T\xFCr wurde ge\xF6ffnet"


- id: xiaomi_single_click
  alias: Flurlicht an
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000156295f
      click_type: single
  action:
    service: light.turn_on
    entity_id: light.flur

- id: xiaomi_double_click
  alias: Flur aus Wohnung an
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000156295f
      click_type: double
  action:
    - service: light.turn_off
      entity_id: light.flur
    - service: light.turn_on
      entity_id: light.wohnung

# hold event is fired when long_click_press is released
# - id: xiaomi_hold
#   alias: Testklick_3
#   trigger:
#     platform: event
#     event_type: click
#     event_data:
#       entity_id: binary_sensor.switch_158d000156295f
#       click_type: hold
#   action:
#   - service: notify.slack_msg
#     data:
#       message: "xiaomi_hold"

- id: xiaomi_long_click_press
  alias: Shutdown
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000156295f
      click_type: long_click_press
  action:
    service: light.turn_off
