- alias: "Aufstehen unter der Woche"
  trigger:
    - platform: time
      hours: 6
      minutes: 30
      seconds: 00
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: homeassistant.turn_on
    entity_id: light.wohnung
    data:
      brightness: 50





