- platform: template
  sensors:
    door:
      value_template: "{{ states.binary_sensor.door_window_sensor_158d00011c8d52.state == 'on' }}"
      device_class: opening
      entity_id:
        - binary_sensor.door_window_sensor_158d00011c8d52