homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 515
  unit_system: metric
  time_zone: Europe/Berlin

frontend:

config:

http:
  api_password: !secret http_password

updater:

discovery:

conversation:

history:

logbook:

sun:

sensor: !include sensor.yaml

tts:
  platform: google

light: !include light.yaml

ifttt:
  key: !secret ifttt

automation: !include automation.yaml

device_tracker: !include device_tracker.yaml


