# views
default_view:
  view: yes
  entities:
    - group.lights
    - group.scenes
    - group.info

devices:
  name: Geräte
  view: yes
  entities:
    # - group.devicegroup
    - group.remote_plugs
    - group.electronic_devices


# groups
lights:
  name: Lichter
  entities:
    - light.wohnung
    - light.kuche
    - light.flur
    - light.gateway_light_286c0788b99e


scenes:
  name: "Szenen"
  entities:
    - switch.netflix_switch


info:
  name: Infos
  entities:
    - sensor.mold_indicator
    - sensor.time
    - sensor.yr_symbol
    - sun.sun
    - sensor.yr_temperature
    - sensor.temperature_158d0001584ffd
    - sensor.yr_humidity
    - sensor.humidity_158d0001584ffd
    - binary_sensor.door_window_sensor_158d00011c8d52
    - binary_sensor.motion_sensor_158d000113c70a

switches:
  name: Switches
  entities:
    - switch.switch_long_press_158d000156295f
    - switch.switch_one_click_158d000156295f
    - switch.switch_double_click_158d000156295f

sensors:
  name: Sensoren
  view: yes
  entities:
    - group.info
    - group.switches
# devicegroup:
#   name: Geräte
#   entities:
    # - device_tracker.oneplus
    # - device_tracker.ulismbp  

remote_plugs:
  name: Steckdosen
  entities:
    - switch.steckdose_alles


electronic_devices:
  name: "Geräte"
  entities:
    - switch.fernseher

scripts:
  name: Skripte
  view: yes
  entities:
    - script.netflix_on
    - script.netflix_off



automation:
  name: automation
  view: yes
  entities: 
    - automation.kuchenlicht_an_bei_bewegung
    - automation.kuchenlicht_aus_ohne_bewegung
    - automation.tur_offnen_licht_an
    - automation.aufstehen_unter_der_woche
    - automation.nachricht_wenn_tur_geoffnet_wird
    - automation.flurlicht_an
    - automation.flur_aus_wohnung_an
    - automation.shutdown