- platform: limitlessled
  bridges:
    - host: 192.168.178.42
      version: 6
      port: 5987
      groups:
      - number: 3
        name: Flur
        type: rgbw
      - number: 2
        name: Küche
        type: rgbw
      - number: 1
        type: rgbw
        name: Wohnung